services:
  nginx-harvest-source:
    image: nginx
    volumes:
      - ./example_data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${HARVEST_SOURCE_PORT}:80"
  db:
      image: postgres:latest
      restart: always
      env_file:
        - .env
      environment:
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_NAME}
      ports:
        - "${DATABASE_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_URI: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}
      FLASK_APP: run.py
      FLASK_ENV: development
    ports:
      - "8080:8080"
    command: flask run --host=0.0.0.0 --port=8080 --reload

volumes:
  postgres_data: