version: "3"

services:
  mdtranslator:
    image: ghcr.io/gsa/mdtranslator:latest
    ports:
      - 3000:3000
  nginx-harvest-source:
    image: nginx
    volumes:
      - ./tests/harvest-sources:/usr/share/nginx/html
      - ./tests/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80