version: "3" 

services:
  nginx-harvest-source:
    image: nginx
    volumes:
      - ./tests/harvest-sources:/usr/share/nginx/html
      - ./tests/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  localstack-container:
    container_name: "localstack-container"
    privileged: true
    image: localstack/localstack:1.3.1
    ports:
      - "4566:4566"
      - "8081:8081"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME=
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - START_WEB=1
    volumes:
      - "./tmp/localstack:/var/lib/localstack"