name: Harvester 2.0 Load Test
on:
  workflow_dispatch:
    
jobs:
  load-test:
    name: H2.0 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
            python-version: 3.9
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: 
        run:
            poetry install
      - name: Run Test
        env:
            SRC_TITLE: 'EPA ScienceHub'
            SRC_URL: 'https://pasteur.epa.gov/metadata.json'
            SRC_OWNER_ORG: '82b85475-f85d-404a-b95b-89d1a42e9f6b'
            SRC_SOURCE_TYPE: 'datajson'
            CKAN_URL: ${{secrets.CKAN_URL}}
            CKAN_API_TOKEN: ${{secrets.CKAN_API_TOKEN}}
        run: |
            poetry run python scripts/load_test.py
