---
name: Tests on Commit
on: [push, pull_request]

env:
  PY_VERSION: "3.9"
  POETRY_VERSION: "1.4.2"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Python Lint
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1

  test:
    runs-on: ubuntu-latest
    name: Pytests
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python ${{ env.PY_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Install Dependencies
        run: |
          poetry env use ${{ env.PY_VERSION }}
          poetry install

      - name: Setup services
        run: docker-compose up -d

      - name: Run Pytest
        run: set -o pipefail; poetry run pytest --junitxml=pytest.xml --cov=harvester | tee pytest-coverage.txt

      - name: Report test coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}
